### ISSUE TITLE
Dependencies improvement suggestion

### ISSUE THREAD

**Issue by stefanGaina** [rdWei/mousice#1]
Hi, I successfully compiled and ran the program but I encountered 2 errors that I think are worth documenting:

cmake .. command failed because "Could NOT find CURL", I think it should be mentioned in the list of dependencies.
./mousice bohemian_rapsody fails to show the image because "chafa: Unknown option --view-size=50x50", I have chafa 1.8.0 installed and it looks like the view-size specifier has been added in 1.14.0, I think it should be mentioned in the readme as well.

**Comment by krymancer** [comment]
Yeah I was unable to compile this on windows because of CURL, but worked fine on arch btw

**Comment by SamueleAmato** [comment]
Thank you for the contribution! Issue resolved in the [latest commit](https://github.com/rdWei/mousice/commit/f2eab89fb434f9e92d621df0d6352ac86ed634ad).
